version: "3.8"

services:
  app:
    image: ghcr.io/onebyone-2024/backend-temporary-for-flutter-base:latest
    container_name: live-tracking-be
    ports:
      - "5556:3000"
    env_file:
      - .env
    restart: unless-stopped
